### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aswinikalyan30**
Fixed typo in README( "lable to label")

### CODE REVIEW

**Review by saumyasrivastava08 — CHANGES_REQUESTED** [review]
Add One section how to fork repo and create PR. in documentation.

**Comment by aswinikalyan30** [comment]
Sure, will do that too

**Comment by aswinikalyan30** [comment]
Have made the necessary changes

**Review by saumyasrivastava08 — APPROVED** [review]
All's good.

**Pull request merged**
